# Generated by Django 5.2.15 on 2026-06-18 09:06

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('integrations', '0001_initial'),
        ('projects', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AlignmentResult',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_deleted', models.BooleanField(default=False)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('requirement_jira_score', models.IntegerField(blank=True, null=True)),
                ('jira_pr_score', models.IntegerField(blank=True, null=True)),
                ('pr_artifact_score', models.IntegerField(blank=True, null=True)),
                ('overall_alignment_score', models.IntegerField()),
                ('alignment_status', models.CharField(default='Aligned', max_length=50)),
                ('confidence', models.IntegerField(default=100)),
                ('explanation', models.TextField(blank=True, null=True)),
                ('score', models.IntegerField()),
                ('summary', models.TextField(blank=True, null=True)),
                ('code_artifact', models.ForeignKey(blank=True, db_column='code_artifact_id', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='alignment_results', to='integrations.codeartifact')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_created', to=settings.AUTH_USER_MODEL)),
                ('jira_story', models.ForeignKey(blank=True, db_column='jira_story_id', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='alignment_results', to='integrations.jirastory')),
                ('project', models.ForeignKey(db_column='project_id', on_delete=django.db.models.deletion.CASCADE, related_name='alignment_results', to='projects.project')),
                ('pull_request', models.ForeignKey(blank=True, db_column='pull_request_id', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='alignment_results', to='integrations.pullrequest')),
                ('requirement_version', models.ForeignKey(db_column='requirement_version_id', on_delete=django.db.models.deletion.CASCADE, related_name='alignment_results', to='projects.requirementversion')),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_updated', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'alignment_results',
            },
        ),
    ]
