version: "1"

services:
  # 1. Django Backend API
  - type: web
    name: django-api
    env: python
    plan: free
    rootDir: apps/django_api
    buildCommand: "bash ./build.sh"
    startCommand: "gunicorn core.wsgi:application --bind 0.0.0.0:$PORT --workers 1 --threads 1 --timeout 120"
    envVars:
      - key: DJANGO_DATABASE_URL
        fromDatabase:
          name: alignment-checker-db
          property: connectionString
      - key: DEBUG
        value: "False"
      - key: SECRET_KEY
        generateValue: true
      - key: OMP_NUM_THREADS
        value: "1"
      - key: MKL_NUM_THREADS
        value: "1"
      - key: OPENBLAS_NUM_THREADS
        value: "1"
      - key: VECLIB_MAXIMUM_THREADS
        value: "1"
      - key: NUMEXPR_NUM_THREADS
        value: "1"

  # 2. Next.js Frontend Web
  - type: web
    name: nextjs-web
    env: node
    plan: free
    rootDir: apps/web
    buildCommand: "npm install && npm run build"
    startCommand: "npm run start"
    envVars:
      - key: NEXT_PUBLIC_API_URL
        value: "UPDATE_THIS_URL_LATER" # We will update this in the dashboard after the backend gets its URL

databases:
  # 3. PostgreSQL Database
  - name: alignment-checker-db
    databaseName: alignment_checker_django
    plan: free
