# Generated by Django 5.2.15 on 2026-06-17 17:51

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('projects', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='PullRequest',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_deleted', models.BooleanField(default=False)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('pr_number', models.IntegerField(db_index=True)),
                ('repository_url', models.CharField(max_length=500)),
                ('title', models.CharField(max_length=500)),
                ('pr_description', models.TextField(blank=True, null=True)),
                ('diff_content', models.TextField(blank=True, null=True)),
                ('status', models.CharField(max_length=20)),
                ('author', models.CharField(blank=True, max_length=255, null=True)),
                ('branch', models.CharField(blank=True, max_length=255, null=True)),
                ('base_branch', models.CharField(blank=True, max_length=255, null=True)),
                ('head_sha', models.CharField(blank=True, max_length=100, null=True)),
                ('merged_at', models.DateTimeField(blank=True, null=True)),
                ('changed_files', models.JSONField(blank=True, default=list)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_created', to=settings.AUTH_USER_MODEL)),
                ('project', models.ForeignKey(db_column='project_id', on_delete=django.db.models.deletion.CASCADE, related_name='pull_requests', to='projects.project')),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_updated', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'pull_requests',
                'unique_together': {('project', 'pr_number')},
            },
        ),
        migrations.CreateModel(
            name='CodeArtifact',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_deleted', models.BooleanField(default=False)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('artifact_type', models.CharField(choices=[('Function', 'Function'), ('Class', 'Class'), ('API Endpoint', 'API Endpoint')], db_index=True, max_length=20)),
                ('artifact_name', models.CharField(db_index=True, max_length=500)),
                ('file_path', models.CharField(max_length=500)),
                ('artifact_metadata', models.JSONField(blank=True, null=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_created', to=settings.AUTH_USER_MODEL)),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_updated', to=settings.AUTH_USER_MODEL)),
                ('pull_request', models.ForeignKey(db_column='pull_request_id', on_delete=django.db.models.deletion.CASCADE, related_name='code_artifacts', to='integrations.pullrequest')),
            ],
            options={
                'db_table': 'code_artifacts',
            },
        ),
        migrations.CreateModel(
            name='JiraStory',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_deleted', models.BooleanField(default=False)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('jira_issue_key', models.CharField(db_index=True, max_length=50)),
                ('title', models.CharField(max_length=500)),
                ('description', models.TextField(blank=True, null=True)),
                ('status', models.CharField(max_length=100)),
                ('story_type', models.CharField(blank=True, max_length=50, null=True)),
                ('epic_key', models.CharField(blank=True, db_index=True, max_length=50, null=True)),
                ('assignee', models.CharField(blank=True, max_length=255, null=True)),
                ('priority', models.CharField(blank=True, max_length=50, null=True)),
                ('external_url', models.CharField(blank=True, max_length=500, null=True)),
                ('labels', models.JSONField(blank=True, default=list)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_created', to=settings.AUTH_USER_MODEL)),
                ('project', models.ForeignKey(db_column='project_id', on_delete=django.db.models.deletion.CASCADE, related_name='jira_stories', to='projects.project')),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_updated', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'jira_stories',
                'unique_together': {('project', 'jira_issue_key')},
            },
        ),
    ]
