# Generated by Django 5.2.15 on 2026-06-20 17:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('integrations', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='codeartifact',
            name='artifact_type',
            field=models.CharField(choices=[('Function', 'Function'), ('Class', 'Class'), ('API Endpoint', 'API Endpoint'), ('Entity', 'Entity'), ('Database Connection', 'Database Connection'), ('UI Layout', 'UI Layout')], db_index=True, max_length=20),
        ),
    ]
