# Generated by Django 5.2.15 on 2026-06-18 12:23

from django.db import migrations
import re

def populate_usernames(apps, schema_editor):
    CustomUser = apps.get_model('authentication', 'CustomUser')
    existing_usernames = set()
    
    for user in CustomUser.objects.all():
        if user.username:
            existing_usernames.add(user.username)
            continue
            
        if user.full_name:
            base_username = re.sub(r'[^a-zA-Z0-9_]', '', user.full_name.lower().replace(' ', '_'))
        else:
            base_username = re.sub(r'[^a-zA-Z0-9_]', '', user.email.split('@')[0].lower())
            
        if not base_username:
            base_username = "user"
            
        username = base_username
        suffix = 1
        while username in existing_usernames:
            username = f"{base_username}{suffix}"
            suffix += 1
            
        user.username = username
        user.save(update_fields=['username'])
        existing_usernames.add(username)

class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0002_customuser_username'),
    ]

    operations = [
        migrations.RunPython(populate_usernames, reverse_code=migrations.RunPython.noop),
    ]
