"""Remove project status

Revision ID: bf263c408395
Revises: 0004
Create Date: 2026-06-17 12:58:35.541666

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'bf263c408395'
down_revision: Union[str, Sequence[str], None] = '0004'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('projects', 'status')
    op.create_index(op.f('ix_users_company_name'), 'users', ['company_name'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_users_company_name'), table_name='users')
    op.add_column('projects', sa.Column('status', sa.VARCHAR(), server_default=sa.text("'Draft'::character varying"), autoincrement=False, nullable=False))
    # ### end Alembic commands ###
